arch: s390x
services:
  - docker
env:
  global:
    - TEST_DIR="$PWD"
    - TEST_SCRIPT="test.sh"
    - BUILD_DIR="$PWD/Logstash"
    - REPO="quay.io/ibmz/logstash"
    - TAG="$REPO:7.9.1"
before_script: 
  - docker login quay.io -u $ROBOT_USER -p $ROBOT_TOKEN
script: 
  - docker build $BUILD_DIR --tag $TAG
after_script:
  - docker push $REPO
